# Generated by Django 5.2.1 on 2025-05-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_cat_dog_rabbit_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
