# Generated by Django 5.2.1 on 2025-05-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_cat_featured_dog_featured_rabbit_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='type',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='type',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='type',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
    ]
