# Generated by Django 5.2.1 on 2025-05-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_cat_type_dog_type_rabbit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='type',
            field=models.CharField(default='Unknown', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='dog',
            name='type',
            field=models.CharField(default='Unknown', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='type',
            field=models.CharField(default='Unknown', editable=False, max_length=20),
        ),
    ]
