# Generated by Django 5.2.1 on 2025-05-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_cat_type_alter_dog_type_alter_rabbit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animal_images/'),
        ),
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animal_images/'),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animal_images/'),
        ),
    ]
