# Generated by Django 5.2.1 on 2025-05-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_cat_image_dog_image_rabbit_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='type',
            new_name='pet_type',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='type',
            new_name='pet_type',
        ),
        migrations.RenameField(
            model_name='rabbit',
            old_name='type',
            new_name='pet_type',
        ),
    ]
