# Generated by Django 5.2.1 on 2025-05-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_type_cat_pet_type_rename_type_dog_pet_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='pet_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dog',
            name='pet_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='pet_type',
            field=models.CharField(max_length=20),
        ),
    ]
