# Generated by Django 5.2.1 on 2025-05-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_cat_pet_type_alter_dog_pet_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='pet_type',
            field=models.CharField(choices=[('cat', 'dog'), ('rabbit', 'rabbit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dog',
            name='pet_type',
            field=models.CharField(choices=[('cat', 'dog'), ('rabbit', 'rabbit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='pet_type',
            field=models.CharField(choices=[('cat', 'dog'), ('rabbit', 'rabbit')], max_length=10),
        ),
    ]
