# Generated by Django 5.2.1 on 2025-06-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_cat_pet_type_alter_dog_pet_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('age', models.PositiveIntegerField(default=1, verbose_name='Age')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=1)),
                ('petType', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('bird', 'Bird'), ('rodent', 'Rodent'), ('reptile', 'Reptile')], default=None, max_length=32)),
                ('intakeMethod', models.TextField(default=None, max_length=128, verbose_name='Intake Method')),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default=None, upload_to='animal_images/')),
                ('adoptability', models.CharField(choices=[('y', 'Available'), ('n', 'Adopted'), ('u', 'Unknown')], default='u', max_length=1)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reptile',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('age', models.PositiveIntegerField(default=1, verbose_name='Age')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=1)),
                ('petType', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('bird', 'Bird'), ('rodent', 'Rodent'), ('reptile', 'Reptile')], default=None, max_length=32)),
                ('intakeMethod', models.TextField(default=None, max_length=128, verbose_name='Intake Method')),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default=None, upload_to='animal_images/')),
                ('adoptability', models.CharField(choices=[('y', 'Available'), ('n', 'Adopted'), ('u', 'Unknown')], default='u', max_length=1)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rodent',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('age', models.PositiveIntegerField(default=1, verbose_name='Age')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=1)),
                ('petType', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('bird', 'Bird'), ('rodent', 'Rodent'), ('reptile', 'Reptile')], default=None, max_length=32)),
                ('intakeMethod', models.TextField(default=None, max_length=128, verbose_name='Intake Method')),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default=None, upload_to='animal_images/')),
                ('adoptability', models.CharField(choices=[('y', 'Available'), ('n', 'Adopted'), ('u', 'Unknown')], default='u', max_length=1)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cat',
            name='pet_type',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='pet_type',
        ),
        migrations.RemoveField(
            model_name='rabbit',
            name='pet_type',
        ),
        migrations.AddField(
            model_name='cat',
            name='adoptability',
            field=models.CharField(choices=[('y', 'Available'), ('n', 'Adopted'), ('u', 'Unknown')], default='u', max_length=1),
        ),
        migrations.AddField(
            model_name='cat',
            name='intakeMethod',
            field=models.TextField(default=None, max_length=128, verbose_name='Intake Method'),
        ),
        migrations.AddField(
            model_name='cat',
            name='petType',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('bird', 'Bird'), ('rodent', 'Rodent'), ('reptile', 'Reptile')], default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='dog',
            name='adoptability',
            field=models.CharField(choices=[('y', 'Available'), ('n', 'Adopted'), ('u', 'Unknown')], default='u', max_length=1),
        ),
        migrations.AddField(
            model_name='dog',
            name='intakeMethod',
            field=models.TextField(default=None, max_length=128, verbose_name='Intake Method'),
        ),
        migrations.AddField(
            model_name='dog',
            name='petType',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('bird', 'Bird'), ('rodent', 'Rodent'), ('reptile', 'Reptile')], default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='adoptability',
            field=models.CharField(choices=[('y', 'Available'), ('n', 'Adopted'), ('u', 'Unknown')], default='u', max_length=1),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='intakeMethod',
            field=models.TextField(default=None, max_length=128, verbose_name='Intake Method'),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='petType',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('bird', 'Bird'), ('rodent', 'Rodent'), ('reptile', 'Reptile')], default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.PositiveIntegerField(default=1, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cat',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='animal_images/'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.PositiveIntegerField(default=1, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='animal_images/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='age',
            field=models.PositiveIntegerField(default=1, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='animal_images/'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
