# Generated by Django 5.2.1 on 2025-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_dragon_alter_cat_pet_type_alter_dog_pet_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('featured', models.BooleanField(default=False)),
                ('pet_type', models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('rabbit', 'rabbit'), ('dragon', 'dragon'), ('fox', 'fox')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='animal_images/')),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='cat',
            name='pet_type',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('rabbit', 'rabbit'), ('dragon', 'dragon'), ('fox', 'fox')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dog',
            name='pet_type',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('rabbit', 'rabbit'), ('dragon', 'dragon'), ('fox', 'fox')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dragon',
            name='pet_type',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('rabbit', 'rabbit'), ('dragon', 'dragon'), ('fox', 'fox')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='pet_type',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('rabbit', 'rabbit'), ('dragon', 'dragon'), ('fox', 'fox')], max_length=10),
        ),
    ]
