# Generated by Django 5.2.1 on 2025-06-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_bird_reptile_rodent_remove_cat_pet_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='image',
            field=models.ImageField(default=None, upload_to='animal_images/'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='intakeMethod',
            field=models.CharField(default='', max_length=32, verbose_name='Intake Method'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(default=None, upload_to='animal_images/'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='intakeMethod',
            field=models.CharField(default='', max_length=32, verbose_name='Intake Method'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(default=None, upload_to='animal_images/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='intakeMethod',
            field=models.CharField(default='', max_length=32, verbose_name='Intake Method'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='image',
            field=models.ImageField(default=None, upload_to='animal_images/'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='intakeMethod',
            field=models.CharField(default='', max_length=32, verbose_name='Intake Method'),
        ),
        migrations.AlterField(
            model_name='reptile',
            name='image',
            field=models.ImageField(default=None, upload_to='animal_images/'),
        ),
        migrations.AlterField(
            model_name='reptile',
            name='intakeMethod',
            field=models.CharField(default='', max_length=32, verbose_name='Intake Method'),
        ),
        migrations.AlterField(
            model_name='rodent',
            name='image',
            field=models.ImageField(default=None, upload_to='animal_images/'),
        ),
        migrations.AlterField(
            model_name='rodent',
            name='intakeMethod',
            field=models.CharField(default='', max_length=32, verbose_name='Intake Method'),
        ),
    ]
