# Generated by Django 5.2.1 on 2025-06-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_fox_alter_cat_pet_type_alter_dog_pet_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dragon',
        ),
        migrations.AlterField(
            model_name='cat',
            name='pet_type',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('rabbit', 'rabbit'), ('fox', 'fox')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dog',
            name='pet_type',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('rabbit', 'rabbit'), ('fox', 'fox')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fox',
            name='pet_type',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('rabbit', 'rabbit'), ('fox', 'fox')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='pet_type',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('rabbit', 'rabbit'), ('fox', 'fox')], max_length=10),
        ),
    ]
