# Generated by Django 5.2.1 on 2025-06-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_bird_image_alter_bird_intakemethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cat',
            name='intakeMethod',
            field=models.CharField(default='u', max_length=32, verbose_name='Intake Method'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='intakeMethod',
            field=models.CharField(default='u', max_length=32, verbose_name='Intake Method'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='intakeMethod',
            field=models.CharField(default='u', max_length=32, verbose_name='Intake Method'),
        ),
        migrations.AlterField(
            model_name='reptile',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reptile',
            name='intakeMethod',
            field=models.CharField(default='u', max_length=32, verbose_name='Intake Method'),
        ),
        migrations.AlterField(
            model_name='rodent',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='rodent',
            name='intakeMethod',
            field=models.CharField(default='u', max_length=32, verbose_name='Intake Method'),
        ),
    ]
