# Generated by Django 5.2.5 on 2025-08-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_bird_gender_alter_cat_gender_and_more'),
        ('pages', '0014_delete_dragon_alter_cat_pet_type_alter_dog_pet_type_and_more'),
    ]

    operations = [
    ]
