# Generated by Django 5.2.5 on 2025-08-28 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_merge_20250828_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('H', 'Hermaphrodite')], max_length=1)),
                ('intake_method', models.CharField(choices=[('Y', 'Available'), ('N', 'Adopted'), ('u', 'Unknown')], max_length=1, verbose_name='Intake Method')),
                ('is_featured', models.BooleanField(default=False)),
                ('image_url', models.ImageField(default=None, upload_to='animal_images/')),
                ('status', models.CharField(choices=[('I', 'Rescued by Inspectors'), ('S', 'Rescue from Stray')], default='', max_length=1, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Bird',
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
        migrations.DeleteModel(
            name='Fox',
        ),
        migrations.DeleteModel(
            name='Rabbit',
        ),
        migrations.DeleteModel(
            name='Reptile',
        ),
        migrations.DeleteModel(
            name='Rodent',
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.breed'),
        ),
        migrations.AddField(
            model_name='breed',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.species'),
        ),
    ]
