# Generated by Django 5.2 on 2025-04-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionForm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetDatabase',
            new_name='animalDatabase',
        ),
    ]
