# Generated by Django 5.2 on 2025-04-03 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionForm', '0002_rename_petdatabase_animaldatabase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='animalDatabase',
            new_name='animals',
        ),
    ]
